// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/user/auth_handler.go

// Package user is a generated GoMock package.
package user

import (
	exception "github.com/1ambda/domain-driven-design-go/service-gateway/internal/exception"
	swagapi "github.com/1ambda/domain-driven-design-go/service-gateway/pkg/generated/swagger/swagserver/swagapi"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAuthHandler is a mock of AuthHandler interface
type MockAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerMockRecorder
}

// MockAuthHandlerMockRecorder is the mock recorder for MockAuthHandler
type MockAuthHandlerMockRecorder struct {
	mock *MockAuthHandler
}

// NewMockAuthHandler creates a new mock instance
func NewMockAuthHandler(ctrl *gomock.Controller) *MockAuthHandler {
	mock := &MockAuthHandler{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthHandler) EXPECT() *MockAuthHandlerMockRecorder {
	return m.recorder
}

// Configure mocks base method
func (m *MockAuthHandler) Configure(handlerRegistry *swagapi.GatewayAPI) {
	m.ctrl.Call(m, "Configure", handlerRegistry)
}

// Configure indicates an expected call of Configure
func (mr *MockAuthHandlerMockRecorder) Configure(handlerRegistry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockAuthHandler)(nil).Configure), handlerRegistry)
}

// Register mocks base method
func (m *MockAuthHandler) Register(uid, email, password string) (*AuthClaim, exception.Exception) {
	ret := m.ctrl.Call(m, "Register", uid, email, password)
	ret0, _ := ret[0].(*AuthClaim)
	ret1, _ := ret[1].(exception.Exception)
	return ret0, ret1
}

// Register indicates an expected call of Register
func (mr *MockAuthHandlerMockRecorder) Register(uid, email, password interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthHandler)(nil).Register), uid, email, password)
}

// Login mocks base method
func (m *MockAuthHandler) Login(uid, password string) (*AuthClaim, exception.Exception) {
	ret := m.ctrl.Call(m, "Login", uid, password)
	ret0, _ := ret[0].(*AuthClaim)
	ret1, _ := ret[1].(exception.Exception)
	return ret0, ret1
}

// Login indicates an expected call of Login
func (mr *MockAuthHandlerMockRecorder) Login(uid, password interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthHandler)(nil).Login), uid, password)
}
